create table if not exists public.issues (
  id bigint generated by default as identity primary key,
  date date not null default current_date,
  title text not null check (length(trim(title)) > 0),
  description text not null,
  root_cause text not null,
  fix text not null,
  tags text[] not null default '{}',
  search_document tsvector generated always as (
    to_tsvector(
      'simple',
      coalesce(title, '') || ' ' ||
      coalesce(description, '') || ' ' ||
      coalesce(root_cause, '') || ' ' ||
      coalesce(fix, '') || ' ' ||
      array_to_string(tags, ' ')
    )
  ) stored
);

create index if not exists issues_date_idx
  on public.issues (date desc, id desc);

create index if not exists issues_tags_idx
  on public.issues using gin (tags);

create index if not exists issues_search_document_idx
  on public.issues using gin (search_document);

alter table public.issues enable row level security;

create policy "Issues are publicly readable"
  on public.issues
  for select
  to anon, authenticated
  using (true);

revoke all on table public.issues from anon, authenticated;
grant select on table public.issues to anon, authenticated;

comment on table public.issues is
  'Sanitized Supabase incident and troubleshooting knowledge base.';
